# Generated by Django 5.0 on 2024-02-06 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('picture', models.ImageField(upload_to='')),
                ('author', models.CharField(default='Guest', max_length=30)),
                ('Email', models.EmailField(blank=True, max_length=254)),
                ('Description', models.TextField(default='Available in library')),
            ],
        ),
    ]
